### ISSUE TITLE
External link checker is confusing on blocks with multiple links

### ISSUE THREAD

**Issue by cbirdsong** [itmaybejj/editoria11y-wp#7]
It's a little confusing to have the whole block marked for review when it has multiple links, only one of which is external:

![CleanShot 2023-04-20 at 08 39 39](https://user-images.githubusercontent.com/1672206/233384238-020230aa-8fb2-4c90-8735-7740d140039b.png)

It might be better if the message was anchored to the links themselves?

![CleanShot 2023-04-20 at 08 49 59](https://user-images.githubusercontent.com/1672206/233387130-e4ad8141-57f8-48ae-935c-79e3e66bbf20.png)

Some rough CSS - it likely would need to be scoped to paragraphs/headings/lists and not _every_ link:
```css
.editor-styles-wrapper :not(.is-selected) a[target="_blank"] {
    position: relative;
    outline: 1px solid #fad859;
    outline-offset: 0;
    box-shadow: 0 0 0 2px #fad859;
    border-radius: 2px;
}

.editor-styles-wrapper :not(.is-selected) a[target*="_blank"]::after {
    content: "Manual check: is opening a new window expected?";
    position: absolute !important;
    bottom: 100% !important;
    left: -2px !important;
    width: auto !important;
    height: auto !important;
    background: #fad859 !important;
    color: #111 !important;
    display: inline-block !important;
    padding: 4px 4px 2px 6px !important;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif !important;
    font-weight: 500 !important;
    font-size: 13px !important;
    line-height: 1 !important;
    border-radius: 2px 0 0 0 !important;
    letter-spacing: 0 !important;
    z-index: 5 !important;
    pointer-events: none !important;
}
```
