### ISSUE TITLE
Append style tags to the body instead of the watched container

### ISSUE THREAD

**Issue by cbirdsong** [itmaybejj/editoria11y-wp#8]
Some `<style>` tags containing CSS for `ed11y-element-result, ed11y-element-panel` are appended to the element you set in "Check content in these containers". When I used `<main>`, this messed up styling on one site because it uses the following CSS:

```css
main > *:last-child:not([class*="has-padding-"]) {
  padding-bottom: clamp(2rem, .98rem + 5.11vw, 6.5rem);
}
```

After the `<style>` tags were injected the last child was always one of those.
